
name: Package Application with Pyinstaller for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        spec: build_windows.spec

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: dist/windows
