
name: Package Application with Pyinstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        spec: build_windows.spec
    - name: Copy Datasets
      run: cp -r datasets dist/windows
    - uses: actions/upload-artifact@v2
      with:
        name: mayuan-windows-amd64.zip
        path: dist/windows
